/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-My-First-Plugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : My First Plugin
 #	author : miyako
 #	2022/08/10
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-My-First-Plugin.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- My First Plugin
            
			case 1 :
				A_command(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void A_command(PA_PluginParameters params) {

	long arg1 = PA_GetLongParameter(params, 1);
	long arg2 = PA_GetLongParameter(params, 2);

	long returnValue = arg1 + arg2;

	PA_ReturnLong(params, returnValue);
}

